service: SWAPIChallenge
useDotenv: true

provider:
 name: aws
 runtime: nodejs14.x
 memorySize: 256
 timeout: 15
 stage: production
 region: us-east-1
 environment:    
    RDS_HOSTNAME: ${env:RDS_HOSTNAME}
    RDS_USERNAME: ${env:RDS_USERNAME}
    RDS_PASSWORD: ${env:RDS_PASSWORD}
    RDS_PORT: ${env:RDS_PORT}
    RDS_DATABASE: ${env:RDS_DATABASE}

functions:
 api:
   handler: lambda.handler
   events:
     - http: ANY {proxy+}
     - http: ANY /